# Before Script
before_script:
  - apt-get update -yqq
  - apt-get install git -yqq
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

# Stages
stages:
  - test

# Image from https://github.com/splitbrain/docker-phpfarm
image: splitbrain/phpfarm:jessie

# PHP5.3
php:5.3:
  stage: test
  script:
      - echo "Running PHPUnit Tests on PHP5.3"
      - php-5.3 vendor/bin/phpunit --colors --debug  --coverage-text

# PHP5.6
php:5.6:
    image: php:5.6
    script:
      - echo "Running PHPUnit Tests on PHP5.6"
      - php vendor/bin/phpunit --colors --debug  --coverage-text